name: noter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_nav_bar: ^5.0.6
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  kt_dart: ^0.10.0
  provider: ^6.0.2
  responsive_framework: ^0.2.0
  rxdart: ^0.27.3
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
